In [11]:
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense, Activation
import pandas as pd
import numpy as np
import csv

In [12]:
data1 = pd.read_csv('paramdataset.csv', header=None)
data2 = pd.read_csv('sensexdata.csv', header=None)

In [13]:
train_x=data1.iloc[:2452,12]
train_x=np.array(train_x).reshape(-1,1)
train_y=data1.iloc[:2452,1]
test_x=data1.iloc[2452:2455,12]
test_x=list(test_x)
test_x=np.array(test_x).reshape(-1,1)
test_y=data1.iloc[2452:2455,1]

In [14]:
def svr_model(train_x, train_y, test_x,y):
    from sklearn.svm import SVR
    import numpy as np

    clf = SVR(C=1.0, epsilon=2.0, gamma=y,verbose=False)
    clf.fit(train_x, train_y)
    predicted_y = clf.predict(test_x)
    print(predicted_y)
    return predicted_y

In [15]:
predict_svr1=svr_model(train_x, train_y, test_x,2e-8)
print(predict_svr1)
print(test_y)

[14483.37226189 14482.07314994 14478.97097587]
[14483.37226189 14482.07314994 14478.97097587]
2452    18835.695
2453    18941.949
2454    19044.591
Name: 1, dtype: float64


In [16]:
train_x=data1.iloc[:2452,12]
train_x=np.array(train_x).reshape(-1,1)
train_y=data1.iloc[:2452,2]
test_x=data1.iloc[2452:2455,12]
#test_x=list(test_x)
test_x=np.array(test_x).reshape(-1,1)
test_y=data1.iloc[2452:2455,2]

In [17]:
predict_svr2=svr_model(train_x, train_y, test_x,2e-8)
print(predict_svr2)
print(test_y)

#print(p)

[14484.08544195 14482.78393041 14479.67580043]
[14484.08544195 14482.78393041 14479.67580043]
2452    19031.10109
2453    19132.22200
2454    19231.28582
Name: 2, dtype: float64


In [18]:
predict_svr3=data1.iloc[2452:2455,3]

In [19]:
train_x=data2.iloc[27:2479,2:5]
train_y=data1.iloc[:2452,4]
test_x=data2.iloc[2479:2482,2:5]
test_y=data1.iloc[2452:2455,4]

In [20]:
predict_svr4=svr_model(train_x, train_y, test_x,100e-8)
print(predict_svr4)
print(test_y)

[63.04302331 64.56540189 63.9811429 ]
[63.04302331 64.56540189 63.9811429 ]
2452    94.113340
2453    93.810688
2454    96.748062
Name: 4, dtype: float64


In [21]:
train_x=data2.iloc[27:2479,2:5]
train_y=data1.iloc[:2452,5]
test_x=data2.iloc[2479:2482,2:5]
test_y=data1.iloc[2452:2455,5]

In [22]:
predict_svr5=svr_model(train_x, train_y, test_x,100e-8)
print(predict_svr5)
print(test_y)

[58.72040902 59.29901547 59.21853399]
[58.72040902 59.29901547 59.21853399]
2452    65.040676
2453    73.395886
2454    80.218824
Name: 5, dtype: float64


In [23]:
train_x=data2.iloc[27:2452,5:7]
train_y=data1.iloc[27:2452,7]
test_x=data2.iloc[2452:2455,5:7]
test_y=data1.iloc[2452:2455,7]

In [24]:
predict_svr7=svr_model(train_x, train_y, test_x,40e-8)
print(predict_svr7)
print(test_y)

[46.96733453 46.30258442 45.57123334]
[46.96733453 46.30258442 45.57123334]
2452    134.142923
2453    163.439463
2454    188.761871
Name: 7, dtype: float64


In [25]:
train_x=data1.iloc[:2452,3]
train_x=np.array(train_x).reshape(-1,1)
train_y=data1.iloc[:2452,5]
test_x=data1.iloc[2452:2455,3]
test_x=np.array(test_x).reshape(-1,1)
test_y=data1.iloc[2452:2455,5]

In [26]:
predict_svr6=svr_model(train_x, train_y, test_x,10e-8)
print(predict_svr6)
print(test_y)

[83.2504657  81.99428618 82.55718453]
[83.2504657  81.99428618 82.55718453]
2452    65.040676
2453    73.395886
2454    80.218824
Name: 5, dtype: float64


In [27]:
train_x=data2.iloc[27:2479,2:5]
train_y=data1.iloc[:2452,7]
test_x=data2.iloc[2479:2482,2:5]
test_y=data1.iloc[2452:2455,7]

In [28]:
predict_svr8=svr_model(train_x, train_y, test_x,10e-8)
print(predict_svr8)
print(test_y)

[125.17975597 126.83584127 126.5972443 ]
[125.17975597 126.83584127 126.5972443 ]
2452    134.142923
2453    163.439463
2454    188.761871
Name: 7, dtype: float64


In [29]:
predict_svr9=data1.iloc[2452:2455,9]

In [30]:
predict_svr10=data1.iloc[2452:2455,10]

In [31]:
print(predict_svr10)
p = pd.DataFrame(
    {'A': predict_svr1,
     'B': predict_svr2,
     'C': predict_svr3,
     'E': predict_svr4,
     'F': predict_svr5,
     'G': predict_svr6,
     'H': predict_svr7,
     'I': predict_svr8,
     'J': predict_svr9,
     'K': predict_svr10,
    })
p.to_csv('testdata.csv', sep=',')

2452    96.224825
2453    88.126593
2454    72.974938
Name: 10, dtype: float64
