In [65]:
from tensorflow.python.keras.models import Sequential
from keras import optimizers
from tensorflow.python.keras.layers import Dense, Activation
import pandas as pd

In [50]:
data = pd.read_csv('paramdataset.csv', header=None)

In [51]:
from sklearn.model_selection import train_test_split
#train_x=data.iloc[:2452,1:11]
#train_y=data.iloc[:2452,12]
#test_x=data.iloc[2452:2455,1:11]
#test_y=data.iloc[2452:2455,12]
train_x, test_x, train_y, test_y = train_test_split(data.iloc[:,1:11], data.iloc[:,12], test_size=0.2, random_state=None, shuffle=False)

In [52]:
#print(test_y)

In [53]:
def svr_model(train_x, train_y, test_x):
    from sklearn.svm import SVR
    import numpy as np

    clf = SVR(C=1.0, epsilon=2.0, gamma=1e-8,verbose=False)
    clf.fit(train_x, train_y)
    predicted_y = clf.predict(test_x)
    print(predicted_y)
    return predicted_y

In [54]:
predict_svr=svr_model(train_x, train_y, test_x)
#print(predict_svr)

[11994.29677106 11998.03456712 12003.15870498 12008.38756803
 12016.50205685 12017.77531862 12020.262413   12030.6190328
 12044.24636963 12049.5005272  12060.7863798  12066.15079101
 12066.71535833 12064.88300956 12068.56512559 12072.36470588
 12074.6755102  12072.42170873 12078.55189041 12083.33240233
 12081.40984163 12081.80083797 12083.08433801 12086.89706629
 12090.82341799 12095.53846241 12099.20017488 12099.12818712
 12098.50788632 12097.54154238 12098.38829531 12095.48459556
 12094.47587457 12093.77564248 12096.57465579 12094.78660912
 12096.19671009 12097.93673627 12097.33656178 12096.92686582
 12096.39244039 12096.67035967 12095.75946233 12093.29207817
 12094.192932   12092.06612295 12092.48521533 12093.43815639
 12093.24553557 12094.57246402 12093.5854668  12095.59992921
 12097.99083558 12098.0642801  12095.70012132 12091.21900734
 12088.11229311 12079.8677223  12067.49516904 12061.34991369
 12051.00849723 12048.24104642 12045.89529868 12046.57454088
 12046.23130588 12047.156

In [55]:
def random_forest_reg(train_x, train_y, test_x):
    from sklearn.ensemble import RandomForestRegressor
    import numpy as np
    rfr = RandomForestRegressor(max_depth=2, random_state=0)
    rfr.fit(train_x, train_y)
    rfr_predicted_y = rfr.predict(test_x)
    return rfr_predicted_y


In [56]:
predict_rf=random_forest_reg(train_x, train_y, test_x)
#print(predict_rf)


In [57]:
def ann_model(train_x, train_y, test_x):
    model = Sequential()
    model.add(Dense(64, activation='sigmoid', kernel_initializer='normal', input_dim=10))
    model.add(Dense(1,activation='linear', kernel_initializer='normal'))
    #sgd = optimizers.SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)

    model.compile(optimizer='sgd', loss = 'mean_squared_error', metrics = ['accuracy'])

    model.fit(train_x, train_y,
              epochs=300,
              batch_size=10)
    ann_predicted_y = model.predict(test_x)
    ann_predicted_y = ann_predicted_y.reshape(-1)
    return ann_predicted_y


In [58]:
predict_ann = ann_model(train_x, train_y, test_x)
#print(predict_ann)
#print(test_y)

Epoch 1/300
1976/1976 [==============================] - 1s 442us/step - loss: 29146240.7753 - acc: 0.0000e+00
Epoch 2/300
1976/1976 [==============================] - 0s 153us/step - loss: 27965764.9970 - acc: 0.0000e+00
Epoch 3/300
1976/1976 [==============================] - 0s 141us/step - loss: 28684473.4251 - acc: 0.0000e+00
Epoch 4/300
1976/1976 [==============================] - 0s 128us/step - loss: 28082220.5759 - acc: 0.0000e+00
Epoch 5/300
1976/1976 [==============================] - 0s 133us/step - loss: 27769079.8016 - acc: 0.0000e+00
Epoch 6/300
1976/1976 [==============================] - 0s 126us/step - loss: 28196440.8158 - acc: 0.0000e+00
Epoch 7/300
1976/1976 [==============================] - 0s 136us/step - loss: 28001424.3912 - acc: 0.0000e+00
Epoch 8/300
1976/1976 [==============================] - 0s 132us/step - loss: 28048170.2227 - acc: 0.0000e+00
Epoch 9/300
1976/1976 [==============================] - 0s 126us/step - loss: 27297568.2434 - acc: 0.0000e+00
E

1976/1976 [==============================] - 0s 137us/step - loss: 28083575.1538 - acc: 0.0000e+00
Epoch 74/300
1976/1976 [==============================] - 0s 142us/step - loss: 28339089.3573 - acc: 0.0000e+00
Epoch 75/300
1976/1976 [==============================] - 0s 141us/step - loss: 28004330.6690 - acc: 0.0000e+00
Epoch 76/300
1976/1976 [==============================] - 0s 135us/step - loss: 28001818.0800 - acc: 0.0000e+00
Epoch 77/300
1976/1976 [==============================] - 0s 140us/step - loss: 27868208.1063 - acc: 0.0000e+00
Epoch 78/300
1976/1976 [==============================] - 0s 149us/step - loss: 28081445.6002 - acc: 0.0000e+00
Epoch 79/300
1976/1976 [==============================] - 0s 146us/step - loss: 28044031.5941 - acc: 0.0000e+00
Epoch 80/300
1976/1976 [==============================] - 0s 139us/step - loss: 28025044.5749 - acc: 0.0000e+00
Epoch 81/300
1976/1976 [==============================] - 0s 133us/step - loss: 27710447.7146 - acc: 0.0000e+00
Epoch

1976/1976 [==============================] - 0s 155us/step - loss: 27820460.7065 - acc: 0.0000e+00
Epoch 146/300
1976/1976 [==============================] - 0s 168us/step - loss: 28866603.8269 - acc: 0.0000e+00
Epoch 147/300
1976/1976 [==============================] - 0s 116us/step - loss: 27841214.3472 - acc: 0.0000e+00
Epoch 148/300
1976/1976 [==============================] - 0s 152us/step - loss: 27770524.5314 - acc: 0.0000e+00
Epoch 149/300
1976/1976 [==============================] - 0s 158us/step - loss: 27736146.8947 - acc: 0.0000e+00
Epoch 150/300
1976/1976 [==============================] - 0s 122us/step - loss: 27715500.3679 - acc: 0.0000e+00
Epoch 151/300
1976/1976 [==============================] - 0s 128us/step - loss: 27752932.0810 - acc: 0.0000e+00
Epoch 152/300
1976/1976 [==============================] - 0s 121us/step - loss: 28008496.9615 - acc: 0.0000e+00
Epoch 153/300
1976/1976 [==============================] - 0s 119us/step - loss: 28184488.9049 - acc: 0.0000e+

1976/1976 [==============================] - 0s 114us/step - loss: 28105715.5951 - acc: 0.0000e+00
Epoch 218/300
1976/1976 [==============================] - 0s 132us/step - loss: 27531912.2581 - acc: 0.0000e+00
Epoch 219/300
1976/1976 [==============================] - 0s 169us/step - loss: 28231867.8305 - acc: 0.0000e+00
Epoch 220/300
1976/1976 [==============================] - 0s 171us/step - loss: 27537518.3087 - acc: 0.0000e+00
Epoch 221/300
1976/1976 [==============================] - 0s 203us/step - loss: 28105768.5587 - acc: 0.0000e+00
Epoch 222/300
1976/1976 [==============================] - 0s 189us/step - loss: 27654262.5779 - acc: 0.0000e+00
Epoch 223/300
1976/1976 [==============================] - 0s 197us/step - loss: 28038264.7743 - acc: 0.0000e+00
Epoch 224/300
1976/1976 [==============================] - 0s 168us/step - loss: 27678510.3234 - acc: 0.0000e+00
Epoch 225/300
1976/1976 [==============================] - 0s 206us/step - loss: 28098022.9443 - acc: 0.0000e+

1976/1976 [==============================] - 0s 121us/step - loss: 28231293.7085 - acc: 0.0000e+00
Epoch 290/300
1976/1976 [==============================] - 0s 123us/step - loss: 27847841.2940 - acc: 0.0000e+00
Epoch 291/300
1976/1976 [==============================] - 0s 121us/step - loss: 27772912.6397 - acc: 0.0000e+00
Epoch 292/300
1976/1976 [==============================] - 0s 118us/step - loss: 28096951.2126 - acc: 0.0000e+00
Epoch 293/300
1976/1976 [==============================] - 0s 125us/step - loss: 28148574.4190 - acc: 0.0000e+00
Epoch 294/300
1976/1976 [==============================] - 0s 125us/step - loss: 28168731.1123 - acc: 0.0000e+00
Epoch 295/300
1976/1976 [==============================] - 0s 117us/step - loss: 28478039.9899 - acc: 0.0000e+00
Epoch 296/300
1976/1976 [==============================] - 0s 131us/step - loss: 27889815.7783 - acc: 0.0000e+00
Epoch 297/300
1976/1976 [==============================] - 0s 131us/step - loss: 28011954.1073 - acc: 0.0000e+

In [59]:
def error_function(test_y, predicted_y):
    import numpy as np
    from math import sqrt
    test = list(test_y)
    MAPE=[(test[i]-predicted_y[i])/test[i] for i in range(len(test))]
    MAPE1=abs((sum(MAPE)*100/len(test)))
    MAE=abs((sum(MAPE)/len(test)))
    rRMSE=[((test[i]-predicted_y[i])/test[i])**2 for i in range(len(test))]
    rRMSE=sqrt(sum(rRMSE)/len(test))
    MSE=[(test[i]-predicted_y[i])**2 for i in range(len(test))]
    MSE=sum(MSE)/len(test)
    #print(MSE)
    return MAPE1,MAE,rRMSE,MSE

In [60]:
print("\t MAPE\t\t\tMAE\t\t\trRMSE\t\t\tMSE")
print("SVR:",error_function(test_y, predict_svr))
print("RF:",error_function(test_y, predict_rf))
print("ANN:",error_function(test_y, predict_ann))

	 MAPE			MAE			rRMSE			MSE
SVR: (31.42279927400136, 0.31422799274001356, 0.3168971158360866, 32447235.879651606)
RF: (1.2057819733976345, 0.012057819733976346, 0.05829984582255547, 993397.0603073634)
ANN: (37.31847407967314, 0.37318474079673136, 0.37507570049998745, 45156429.919785514)


In [61]:
test = pd.read_csv('testdata.csv')

In [62]:
train_x=data.iloc[:2452,1:11]
train_y=data.iloc[:2452,12]
test_x=test.iloc[:,1:11]
test_y=data.iloc[2452:2455,12]
#print(test_x)

In [63]:
predict_svr=svr_model(train_x, train_y, test_x)
print(predict_svr)
predict_rf=random_forest_reg(train_x, train_y, test_x)
print(predict_rf)
predict_ann = ann_model(train_x, train_y, test_x)
print(predict_ann)
print(test_y)

[14102.35269824 14102.73182602 14101.87428308]
[14102.35269824 14102.73182602 14101.87428308]
[14261.15634187 14261.15634187 14261.15634187]
Epoch 1/300
2452/2452 [==============================] - 1s 306us/step - loss: 29871351.5567 - acc: 0.0000e+00
Epoch 2/300
2452/2452 [==============================] - 0s 114us/step - loss: 29379237.5710 - acc: 0.0000e+00
Epoch 3/300
2452/2452 [==============================] - 0s 118us/step - loss: 29040889.8670 - acc: 0.0000e+00
Epoch 4/300
2452/2452 [==============================] - 0s 108us/step - loss: 29588771.4192 - acc: 0.0000e+00
Epoch 5/300
2452/2452 [==============================] - 0s 114us/step - loss: 29233788.2635 - acc: 0.0000e+00
Epoch 6/300
2452/2452 [==============================] - 0s 111us/step - loss: 29579697.1803 - acc: 0.0000e+00
Epoch 7/300
2452/2452 [==============================] - 0s 113us/step - loss: 29129920.4543 - acc: 0.0000e+00
Epoch 8/300
2452/2452 [==============================] - 0s 112us/step - loss: 290

2452/2452 [==============================] - 0s 79us/step - loss: 29128132.8467 - acc: 0.0000e+00
Epoch 73/300
2452/2452 [==============================] - 0s 72us/step - loss: 29087516.1109 - acc: 0.0000e+00
Epoch 74/300
2452/2452 [==============================] - 0s 68us/step - loss: 29032658.8695 - acc: 0.0000e+00
Epoch 75/300
2452/2452 [==============================] - 0s 70us/step - loss: 29194591.6150 - acc: 0.0000e+00
Epoch 76/300
2452/2452 [==============================] - 0s 77us/step - loss: 29353731.4380 - acc: 0.0000e+00
Epoch 77/300
2452/2452 [==============================] - 0s 72us/step - loss: 29081990.9094 - acc: 0.0000e+00
Epoch 78/300
2452/2452 [==============================] - 0s 72us/step - loss: 28926542.0938 - acc: 0.0000e+00
Epoch 79/300
2452/2452 [==============================] - 0s 100us/step - loss: 29127926.7186 - acc: 0.0000e+00
Epoch 80/300
2452/2452 [==============================] - 0s 98us/step - loss: 29120188.7268 - acc: 0.0000e+00
Epoch 81/300


2452/2452 [==============================] - 0s 133us/step - loss: 29196744.3340 - acc: 0.0000e+00
Epoch 146/300
2452/2452 [==============================] - 0s 136us/step - loss: 28874720.8206 - acc: 0.0000e+00
Epoch 147/300
2452/2452 [==============================] - 0s 106us/step - loss: 28772244.9429 - acc: 0.0000e+00
Epoch 148/300
2452/2452 [==============================] - 0s 101us/step - loss: 29345806.7830 - acc: 0.0000e+00
Epoch 149/300
2452/2452 [==============================] - 0s 120us/step - loss: 28865417.0591 - acc: 0.0000e+00
Epoch 150/300
2452/2452 [==============================] - 0s 124us/step - loss: 29236539.4350 - acc: 0.0000e+00
Epoch 151/300
2452/2452 [==============================] - 0s 140us/step - loss: 29363652.6052 - acc: 0.0000e+00
Epoch 152/300
2452/2452 [==============================] - 0s 146us/step - loss: 29225590.3157 - acc: 0.0000e+00
Epoch 153/300
2452/2452 [==============================] - 0s 145us/step - loss: 29166345.2953 - acc: 0.0000e+

2452/2452 [==============================] - 0s 150us/step - loss: 29322222.8874 - acc: 0.0000e+00
Epoch 218/300
2452/2452 [==============================] - 0s 119us/step - loss: 29370927.0612 - acc: 0.0000e+00
Epoch 219/300
2452/2452 [==============================] - 0s 114us/step - loss: 29183446.6827 - acc: 0.0000e+00
Epoch 220/300
2452/2452 [==============================] - 0s 114us/step - loss: 29118399.4662 - acc: 0.0000e+00
Epoch 221/300
2452/2452 [==============================] - 0s 122us/step - loss: 29270736.1542 - acc: 0.0000e+00
Epoch 222/300
2452/2452 [==============================] - 0s 109us/step - loss: 28915826.0865 - acc: 0.0000e+00
Epoch 223/300
2452/2452 [==============================] - 0s 91us/step - loss: 29371266.6036 - acc: 0.0000e+00
Epoch 224/300
2452/2452 [==============================] - 0s 100us/step - loss: 28998764.6884 - acc: 0.0000e+00
Epoch 225/300
2452/2452 [==============================] - 0s 116us/step - loss: 29362255.0954 - acc: 0.0000e+0

2452/2452 [==============================] - 0s 89us/step - loss: 28994297.8409 - acc: 0.0000e+00
Epoch 290/300
2452/2452 [==============================] - 0s 97us/step - loss: 28862827.3042 - acc: 0.0000e+00
Epoch 291/300
2452/2452 [==============================] - 0s 113us/step - loss: 29011301.9168 - acc: 0.0000e+00
Epoch 292/300
2452/2452 [==============================] - 0s 102us/step - loss: 29108623.1117 - acc: 0.0000e+00
Epoch 293/300
2452/2452 [==============================] - 0s 96us/step - loss: 28907139.3206 - acc: 0.0000e+00
Epoch 294/300
2452/2452 [==============================] - 0s 103us/step - loss: 29177083.8874 - acc: 0.0000e+00
Epoch 295/300
2452/2452 [==============================] - 0s 102us/step - loss: 29249699.8222 - acc: 0.0000e+00
Epoch 296/300
2452/2452 [==============================] - 0s 102us/step - loss: 29128759.6778 - acc: 0.0000e+00
Epoch 297/300
2452/2452 [==============================] - 0s 105us/step - loss: 28894655.8948 - acc: 0.0000e+00


In [64]:
print("\t MAPE\t\t\tMAE\t\t\trRMSE\t\t\tMSE")
print("SVR:",error_function(test_y, predict_svr))
print("RF:",error_function(test_y, predict_rf))
print("ANN:",error_function(test_y, predict_ann))

	 MAPE			MAE			rRMSE			MSE
SVR: (27.34041461208531, 0.2734041461208531, 0.27341281615844554, 28163458.800599515)
RF: (26.522041682192935, 0.2652204168219294, 0.2652294484374747, 26502890.309465926)
ANN: (34.6410830221782, 0.34641083022178204, 0.346416301394597, 45209813.173992015)
