In [1]:
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense, Activation
import pandas as pd
import numpy as np
import csv

In [2]:
data1 = pd.read_csv('paramdataset.csv', header=None)
data2 = pd.read_csv('nifty.csv', header=None)

In [3]:
train_x=data1.iloc[:2452,12]
train_x=np.array(train_x).reshape(-1,1)
train_y=data1.iloc[:2452,1]
test_x=data1.iloc[2452:2455,12]
test_x=list(test_x)
test_x=np.array(test_x).reshape(-1,1)
test_y=data1.iloc[2452:2455,1]

In [4]:
def svr_model(train_x, train_y, test_x,y):
    from sklearn.svm import SVR
    import numpy as np

    clf = SVR(C=1.0, epsilon=2.0, gamma=y,verbose=False)
    clf.fit(train_x, train_y)
    predicted_y = clf.predict(test_x)
    print(predicted_y)
    return predicted_y

In [5]:
predict_svr1=svr_model(train_x, train_y, test_x,2e-8)
print(predict_svr1)
print(test_y)

[4308.85331136 4309.8925525  4312.68365228]
[4308.85331136 4309.8925525  4312.68365228]
2452    5726.910
2453    5759.805
2454    5791.415
Name: 1, dtype: float64


In [6]:
train_x=data1.iloc[:2452,12]
train_x=np.array(train_x).reshape(-1,1)
train_y=data1.iloc[:2452,2]
test_x=data1.iloc[2452:2455,12]
#test_x=list(test_x)
test_x=np.array(test_x).reshape(-1,1)
test_y=data1.iloc[2452:2455,2]

In [7]:
predict_svr2=svr_model(train_x, train_y, test_x,2e-8)
print(predict_svr2)
print(test_y)

#print(p)

[4310.82202207 4311.86237891 4314.65647892]
[4310.82202207 4311.86237891 4314.65647892]
2452    5786.906364
2453    5818.468182
2454    5849.576364
Name: 2, dtype: float64


In [8]:
predict_svr3=data1.iloc[2452:2455,3]

In [9]:
train_x=data2.iloc[27:2479,2:5]
train_y=data1.iloc[:2452,4]
test_x=data2.iloc[2479:2482,2:5]
test_y=data1.iloc[2452:2455,4]

In [10]:
predict_svr4=svr_model(train_x, train_y, test_x,100e-8)
print(predict_svr4)
print(test_y)

[74.25210719 74.6085606  74.54644403]
[74.25210719 74.6085606  74.54644403]
2452    97.177879
2453    95.145903
2454    96.661891
Name: 4, dtype: float64


In [11]:
train_x=data2.iloc[27:2479,2:5]
train_y=data1.iloc[:2452,5]
test_x=data2.iloc[2479:2482,2:5]
test_y=data1.iloc[2452:2455,5]

In [12]:
predict_svr5=svr_model(train_x, train_y, test_x,100e-8)
print(predict_svr5)
print(test_y)

[62.90123338 63.32519737 63.29222197]
[62.90123338 63.32519737 63.29222197]
2452    64.946212
2453    73.447480
2454    80.211289
Name: 5, dtype: float64


In [13]:
train_x=data2.iloc[27:2452,5:7]
train_y=data1.iloc[27:2452,7]
test_x=data2.iloc[2452:2455,5:7]
test_y=data1.iloc[2452:2455,7]

In [14]:
predict_svr7=svr_model(train_x, train_y, test_x,40e-8)
print(predict_svr7)
print(test_y)

[-8.6973678  -8.9869565  -9.12633344]
[-8.6973678  -8.9869565  -9.12633344]
2452    41.224876
2453    50.546478
2454    58.448887
Name: 7, dtype: float64


In [15]:
train_x=data1.iloc[:2452,3]
train_x=np.array(train_x).reshape(-1,1)
train_y=data1.iloc[:2452,5]
test_x=data1.iloc[2452:2455,3]
test_x=np.array(test_x).reshape(-1,1)
test_y=data1.iloc[2452:2455,5]

In [16]:
predict_svr6=svr_model(train_x, train_y, test_x,10e-8)
print(predict_svr6)
print(test_y)

[73.06595612 72.02237132 72.59239888]
[73.06595612 72.02237132 72.59239888]
2452    64.946212
2453    73.447480
2454    80.211289
Name: 5, dtype: float64


In [17]:
train_x=data2.iloc[27:2479,2:5]
train_y=data1.iloc[:2452,7]
test_x=data2.iloc[2479:2482,2:5]
test_y=data1.iloc[2452:2455,7]

In [18]:
predict_svr8=svr_model(train_x, train_y, test_x,10e-8)
print(predict_svr8)
print(test_y)

[38.22248349 38.75534539 38.737319  ]
[38.22248349 38.75534539 38.737319  ]
2452    41.224876
2453    50.546478
2454    58.448887
Name: 7, dtype: float64


In [19]:
predict_svr9=data1.iloc[2452:2455,9]

In [20]:
predict_svr10=data1.iloc[2452:2455,10]

In [21]:
print(predict_svr10)
p = pd.DataFrame(
    {'A': predict_svr1,
     'B': predict_svr2,
     'C': predict_svr3,
     'E': predict_svr4,
     'F': predict_svr5,
     'G': predict_svr6,
     'H': predict_svr7,
     'I': predict_svr8,
     'J': predict_svr9,
     'K': predict_svr10,
    })
p.to_csv('testdata.csv', sep=',')

2452    87.661825
2453    80.938888
2454    67.359995
Name: 10, dtype: float64
