In [100]:
from tensorflow.python.keras.models import Sequential
from keras import optimizers
from tensorflow.python.keras.layers import Dense, Activation
import pandas as pd

In [85]:
data = pd.read_csv('paramdataset.csv', header=None)

In [86]:
from sklearn.model_selection import train_test_split
#train_x=data.iloc[:2452,1:11]
#train_y=data.iloc[:2452,12]
#test_x=data.iloc[2452:2455,1:11]
#test_y=data.iloc[2452:2455,12]
train_x, test_x, train_y, test_y = train_test_split(data.iloc[:,1:11], data.iloc[:,12], test_size=0.2, random_state=None, shuffle=False)

In [87]:
#print(test_y)

In [88]:
def svr_model(train_x, train_y, test_x):
    from sklearn.svm import SVR
    import numpy as np

    clf = SVR(C=1.0, epsilon=2.0, gamma=1e-8,verbose=False)
    clf.fit(train_x, train_y)
    predicted_y = clf.predict(test_x)
    print(predicted_y)
    return predicted_y

In [89]:
predict_svr=svr_model(train_x, train_y, test_x)
#print(predict_svr)

[3617.17652563 3615.76737652 3613.11764633 3610.57928705 3609.17385619
 3606.31955507 3602.58883812 3599.33849076 3597.34084186 3595.18759332
 3593.82854938 3592.90152941 3592.98015021 3592.37171161 3590.72352227
 3588.67753095 3587.09024276 3584.46412255 3582.1592815  3581.17077259
 3578.57287408 3576.3111733  3573.19259675 3570.0066636  3567.17441104
 3565.90185398 3566.4442484  3567.47254557 3568.3627252  3569.62427255
 3570.39938639 3571.74689401 3572.80504924 3573.62870306 3572.49742455
 3571.41130354 3570.21309908 3571.14155755 3572.05377838 3572.74879963
 3572.90906734 3573.52818141 3574.40983694 3574.95214115 3575.63215035
 3576.89929957 3576.98535398 3577.04363637 3576.27932569 3574.80650029
 3573.60243599 3572.88949109 3572.93962731 3573.55399401 3575.70195968
 3577.72665744 3580.47365265 3583.21838562 3586.39391562 3589.58783849
 3593.23581955 3596.48469228 3598.9606855  3600.99655642 3601.8524033
 3601.90314353 3602.93184254 3602.82819598 3601.56090322 3600.5191133
 3600.51

In [90]:
def random_forest_reg(train_x, train_y, test_x):
    from sklearn.ensemble import RandomForestRegressor
    import numpy as np
    rfr = RandomForestRegressor(max_depth=2, random_state=0)
    rfr.fit(train_x, train_y)
    rfr_predicted_y = rfr.predict(test_x)
    return rfr_predicted_y


In [91]:
predict_rf=random_forest_reg(train_x, train_y, test_x)
#print(predict_rf)


In [92]:
def ann_model(train_x, train_y, test_x):
    model = Sequential()
    model.add(Dense(64, activation='sigmoid', kernel_initializer='normal', input_dim=10))
    model.add(Dense(1,activation='linear', kernel_initializer='normal'))
    #sgd = optimizers.SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)

    model.compile(optimizer='sgd', loss = 'mean_squared_error', metrics = ['accuracy'])

    model.fit(train_x, train_y,
              epochs=300,
              batch_size=10)
    ann_predicted_y = model.predict(test_x)
    ann_predicted_y = ann_predicted_y.reshape(-1)
    return ann_predicted_y


In [93]:
predict_ann = ann_model(train_x, train_y, test_x)
#print(predict_ann)
#print(test_y)

Epoch 1/300
1976/1976 [==============================] - 1s 277us/step - loss: 2436177.9397 - acc: 0.0000e+00
Epoch 2/300
1976/1976 [==============================] - 0s 84us/step - loss: 2353373.2347 - acc: 0.0000e+00
Epoch 3/300
1976/1976 [==============================] - 0s 100us/step - loss: 2360610.6456 - acc: 0.0000e+00
Epoch 4/300
1976/1976 [==============================] - 0s 94us/step - loss: 2336300.7054 - acc: 0.0000e+00
Epoch 5/300
1976/1976 [==============================] - 0s 84us/step - loss: 2337619.8114 - acc: 0.0000e+00
Epoch 6/300
1976/1976 [==============================] - 0s 94us/step - loss: 2357241.6955 - acc: 0.0000e+00
Epoch 7/300
1976/1976 [==============================] - 0s 83us/step - loss: 2348767.0057 - acc: 0.0000e+00
Epoch 8/300
1976/1976 [==============================] - 0s 98us/step - loss: 2382613.1685 - acc: 0.0000e+00
Epoch 9/300
1976/1976 [==============================] - 0s 97us/step - loss: 2393920.3875 - acc: 0.0000e+00
Epoch 10/300
1976

1976/1976 [==============================] - 0s 83us/step - loss: 2377861.5694 - acc: 0.0000e+00
Epoch 76/300
1976/1976 [==============================] - 0s 74us/step - loss: 2363332.0521 - acc: 0.0000e+00
Epoch 77/300
1976/1976 [==============================] - 0s 84us/step - loss: 2360889.1974 - acc: 0.0000e+00
Epoch 78/300
1976/1976 [==============================] - 0s 90us/step - loss: 2361842.0190 - acc: 0.0000e+00
Epoch 79/300
1976/1976 [==============================] - 0s 86us/step - loss: 2363019.9357 - acc: 0.0000e+00
Epoch 80/300
1976/1976 [==============================] - 0s 88us/step - loss: 2353257.6478 - acc: 0.0000e+00
Epoch 81/300
1976/1976 [==============================] - 0s 85us/step - loss: 2393718.5180 - acc: 0.0000e+00
Epoch 82/300
1976/1976 [==============================] - 0s 77us/step - loss: 2366002.2174 - acc: 0.0000e+00
Epoch 83/300
1976/1976 [==============================] - 0s 89us/step - loss: 2348558.3543 - acc: 0.0000e+00
Epoch 84/300
1976/1976 

1976/1976 [==============================] - 0s 88us/step - loss: 2389754.7435 - acc: 0.0000e+00
Epoch 149/300
1976/1976 [==============================] - 0s 90us/step - loss: 2354531.1583 - acc: 0.0000e+00
Epoch 150/300
1976/1976 [==============================] - 0s 111us/step - loss: 2356095.4075 - acc: 0.0000e+00
Epoch 151/300
1976/1976 [==============================] - 0s 102us/step - loss: 2370971.8698 - acc: 0.0000e+00
Epoch 152/300
1976/1976 [==============================] - 0s 109us/step - loss: 2351864.0776 - acc: 0.0000e+00
Epoch 153/300
1976/1976 [==============================] - 0s 115us/step - loss: 2339861.2638 - acc: 0.0000e+00
Epoch 154/300
1976/1976 [==============================] - 0s 114us/step - loss: 2360398.6895 - acc: 0.0000e+00
Epoch 155/300
1976/1976 [==============================] - 0s 104us/step - loss: 2371920.6588 - acc: 0.0000e+00
Epoch 156/300
1976/1976 [==============================] - 0s 101us/step - loss: 2344354.6216 - acc: 0.0000e+00
Epoch 15

1976/1976 [==============================] - 0s 88us/step - loss: 2357722.8311 - acc: 0.0000e+00
Epoch 222/300
1976/1976 [==============================] - 0s 80us/step - loss: 2381439.1337 - acc: 0.0000e+00
Epoch 223/300
1976/1976 [==============================] - 0s 88us/step - loss: 2360893.1791 - acc: 0.0000e+00
Epoch 224/300
1976/1976 [==============================] - 0s 79us/step - loss: 2360068.8439 - acc: 0.0000e+00
Epoch 225/300
1976/1976 [==============================] - 0s 76us/step - loss: 2394001.7428 - acc: 0.0000e+00
Epoch 226/300
1976/1976 [==============================] - 0s 84us/step - loss: 2380200.0221 - acc: 0.0000e+00
Epoch 227/300
1976/1976 [==============================] - 0s 84us/step - loss: 2388007.4319 - acc: 0.0000e+00
Epoch 228/300
1976/1976 [==============================] - 0s 82us/step - loss: 2337614.2672 - acc: 0.0000e+00
Epoch 229/300
1976/1976 [==============================] - 0s 87us/step - loss: 2381003.3167 - acc: 0.0000e+00
Epoch 230/300
1

1976/1976 [==============================] - 0s 85us/step - loss: 2380455.4675 - acc: 0.0000e+00
Epoch 295/300
1976/1976 [==============================] - 0s 85us/step - loss: 2393207.8568 - acc: 0.0000e+00
Epoch 296/300
1976/1976 [==============================] - 0s 77us/step - loss: 2311477.9934 - acc: 0.0000e+00
Epoch 297/300
1976/1976 [==============================] - 0s 88us/step - loss: 2362342.3878 - acc: 0.0000e+00
Epoch 298/300
1976/1976 [==============================] - 0s 72us/step - loss: 2360699.8088 - acc: 0.0000e+00
Epoch 299/300
1976/1976 [==============================] - 0s 84us/step - loss: 2355602.3849 - acc: 0.0000e+00
Epoch 300/300
1976/1976 [==============================] - 0s 85us/step - loss: 2358937.0920 - acc: 0.0000e+00


In [94]:
def error_function(test_y, predicted_y):
    import numpy as np
    from math import sqrt
    test = list(test_y)
    MAPE=[(test[i]-predicted_y[i])/test[i] for i in range(len(test))]
    MAPE1=abs((sum(MAPE)*100/len(test)))
    MAE=abs((sum(MAPE)/len(test)))
    rRMSE=[((test[i]-predicted_y[i])/test[i])**2 for i in range(len(test))]
    rRMSE=sqrt(sum(rRMSE)/len(test))
    MSE=[(test[i]-predicted_y[i])**2 for i in range(len(test))]
    MSE=sum(MSE)/len(test)
    #print(MSE)
    return MAPE1,MAE,rRMSE,MSE

In [95]:
print("\t MAPE\t\t\tMAE\t\t\trRMSE\t\t\tMSE")
print("SVR:",error_function(test_y, predict_svr))
print("Random_forest:",error_function(test_y, predict_rf))
print("ANN:",error_function(test_y, predict_ann))

	 MAPE			MAE			rRMSE			MSE
SVR: (32.98506879504459, 0.3298506879504459, 0.3318621384967826, 3226751.3018082827)
Random_forest: (0.5368159379520007, 0.0053681593795200065, 0.056989789517088135, 89744.33060863409)
ANN: (31.8952042172396, 0.318952042172396, 0.3216543703125145, 3044287.100811888)


In [96]:
test = pd.read_csv('testdata.csv')

In [97]:
train_x=data.iloc[:2452,1:11]
train_y=data.iloc[:2452,12]
test_x=test.iloc[:,1:11]
test_y=data.iloc[2452:2455,12]
print(test_x)

             A            B       C          E          F          G  \
0  4308.853311  4310.822022  317.70  74.252107  62.901233  73.065956   
1  4309.892553  4311.862379  285.70  74.608561  63.325197  72.022371   
2  4312.683652  4314.656479  303.15  74.546444  63.292222  72.592399   

          H          I          J          K  
0 -8.697368  38.222483  15.855355  87.661825  
1 -8.986956  38.755345  65.406427  80.938888  
2 -9.126333  38.737319  11.239749  67.359995  


In [98]:
predict_svr=svr_model(train_x, train_y, test_x)
print(predict_svr)
predict_rf=random_forest_reg(train_x, train_y, test_x)
print(predict_rf)
predict_ann = ann_model(train_x, train_y, test_x)
print(predict_ann)
print(test_y)

[4132.32834946 4132.46537749 4132.80416398]
[4132.32834946 4132.46537749 4132.80416398]
[4232.96163231 4232.96163231 4232.96163231]
Epoch 1/300
2452/2452 [==============================] - 1s 234us/step - loss: 2569932.7371 - acc: 0.0000e+00
Epoch 2/300
2452/2452 [==============================] - 0s 88us/step - loss: 2512780.2674 - acc: 0.0000e+00
Epoch 3/300
2452/2452 [==============================] - 0s 84us/step - loss: 2496470.5820 - acc: 0.0000e+00
Epoch 4/300
2452/2452 [==============================] - 0s 85us/step - loss: 2502139.5336 - acc: 0.0000e+00
Epoch 5/300
2452/2452 [==============================] - 0s 82us/step - loss: 2508503.1256 - acc: 0.0000e+00
Epoch 6/300
2452/2452 [==============================] - 0s 97us/step - loss: 2533296.6566 - acc: 0.0000e+00
Epoch 7/300
2452/2452 [==============================] - 0s 93us/step - loss: 2537455.8368 - acc: 0.0000e+00
Epoch 8/300
2452/2452 [==============================] - 0s 85us/step - loss: 2492470.6262 - acc: 0.0000

2452/2452 [==============================] - 0s 85us/step - loss: 2524087.1815 - acc: 0.0000e+00
Epoch 74/300
2452/2452 [==============================] - 0s 88us/step - loss: 2557623.6646 - acc: 4.0783e-04
Epoch 75/300
2452/2452 [==============================] - 0s 83us/step - loss: 2518951.6587 - acc: 0.0000e+00
Epoch 76/300
2452/2452 [==============================] - 0s 84us/step - loss: 2549817.9598 - acc: 0.0000e+00
Epoch 77/300
2452/2452 [==============================] - 0s 80us/step - loss: 2517796.5061 - acc: 0.0000e+00
Epoch 78/300
2452/2452 [==============================] - 0s 81us/step - loss: 2496562.9863 - acc: 0.0000e+00
Epoch 79/300
2452/2452 [==============================] - 0s 82us/step - loss: 2496023.1394 - acc: 0.0000e+00
Epoch 80/300
2452/2452 [==============================] - 0s 84us/step - loss: 2499483.3398 - acc: 0.0000e+00
Epoch 81/300
2452/2452 [==============================] - 0s 83us/step - loss: 2533711.9515 - acc: 0.0000e+00
Epoch 82/300
2452/2452 

2452/2452 [==============================] - 0s 112us/step - loss: 2497497.9426 - acc: 0.0000e+00
Epoch 148/300
2452/2452 [==============================] - 0s 96us/step - loss: 2509666.1296 - acc: 0.0000e+00
Epoch 149/300
2452/2452 [==============================] - 0s 92us/step - loss: 2482187.9464 - acc: 0.0000e+00
Epoch 150/300
2452/2452 [==============================] - 0s 105us/step - loss: 2498134.0411 - acc: 0.0000e+00
Epoch 151/300
2452/2452 [==============================] - 0s 93us/step - loss: 2530843.9703 - acc: 0.0000e+00
Epoch 152/300
2452/2452 [==============================] - 0s 86us/step - loss: 2530544.1526 - acc: 0.0000e+00
Epoch 153/300
2452/2452 [==============================] - 0s 118us/step - loss: 2475677.6163 - acc: 0.0000e+00
Epoch 154/300
2452/2452 [==============================] - 0s 100us/step - loss: 2519131.1038 - acc: 0.0000e+00
Epoch 155/300
2452/2452 [==============================] - 0s 121us/step - loss: 2529636.6509 - acc: 0.0000e+00
Epoch 156/

2452/2452 [==============================] - 0s 100us/step - loss: 2520002.8742 - acc: 0.0000e+00
Epoch 221/300
2452/2452 [==============================] - 0s 98us/step - loss: 2540474.1808 - acc: 0.0000e+00
Epoch 222/300
2452/2452 [==============================] - 0s 99us/step - loss: 2517642.0930 - acc: 0.0000e+00
Epoch 223/300
2452/2452 [==============================] - 0s 123us/step - loss: 2513208.4009 - acc: 0.0000e+00
Epoch 224/300
2452/2452 [==============================] - 0s 118us/step - loss: 2533474.2072 - acc: 0.0000e+00
Epoch 225/300
2452/2452 [==============================] - 0s 187us/step - loss: 2519680.8155 - acc: 0.0000e+00
Epoch 226/300
2452/2452 [==============================] - 0s 120us/step - loss: 2514373.5298 - acc: 0.0000e+00
Epoch 227/300
2452/2452 [==============================] - 0s 123us/step - loss: 2549188.6487 - acc: 0.0000e+00
Epoch 228/300
2452/2452 [==============================] - 0s 101us/step - loss: 2516709.2201 - acc: 0.0000e+00
Epoch 22

Epoch 293/300
2452/2452 [==============================] - 0s 76us/step - loss: 2567419.6072 - acc: 0.0000e+00
Epoch 294/300
2452/2452 [==============================] - 0s 78us/step - loss: 2508261.9976 - acc: 0.0000e+00
Epoch 295/300
2452/2452 [==============================] - 0s 77us/step - loss: 2515883.2260 - acc: 0.0000e+00
Epoch 296/300
2452/2452 [==============================] - 0s 94us/step - loss: 2503297.4416 - acc: 0.0000e+00
Epoch 297/300
2452/2452 [==============================] - 0s 70us/step - loss: 2490420.7171 - acc: 0.0000e+00
Epoch 298/300
2452/2452 [==============================] - 0s 82us/step - loss: 2521903.2023 - acc: 0.0000e+00
Epoch 299/300
2452/2452 [==============================] - 0s 99us/step - loss: 2521704.3960 - acc: 0.0000e+00
Epoch 300/300
2452/2452 [==============================] - 0s 98us/step - loss: 2551872.3191 - acc: 0.0000e+00
[3826.9612 3826.9612 3826.9612]
2452    5889.25
2453    5900.50
2454    5930.90
Name: 12, dtype: float64


In [99]:
print("\t MAPE\t\t\tMAE\t\t\trRMSE\t\t\tMSE")
print("SVR:",error_function(test_y, predict_svr))
print("Random_forest:",error_function(test_y, predict_rf))
print("ANN:",error_function(test_y, predict_ann))

	 MAPE			MAE			rRMSE			MSE
SVR: (30.038085987486568, 0.3003808598748657, 0.30038783325849916, 3148622.9160252213)
Random_forest: (28.33785795661908, 0.2833785795661908, 0.2833865932313797, 2802323.355029534)
ANN: (35.211263504115486, 0.3521126350411549, 0.352117906598595, 4326385.650990914)
